### PR TITLE
Converted to Python3 + style fix

### PR DESCRIPTION
**Pull request by haizaar**
Converted to work with Python3 (only) + style fixes by `black`

### CODE REVIEW

**Comment by salrashid123** [comment]
thanks for the PR.   the ability to sign in 'keyless' mode is easier now with impersonated_credentials.. that allows for generating signedurl via the client library

```python
import datetime

from google.cloud import storage
from google.auth import impersonated_credentials

import google.auth
import google.auth.transport.requests

bucket_name = 'fabled-ray-104117'
blob_name = 'foo.txt'

source_credentials, project = google.auth.default()

target_credentials = impersonated_credentials.Credentials(
  source_credentials=source_credentials,
  target_principal='impersonated-account%40fabled-ray-104117.iam.gserviceaccount.com',
  target_scopes = ['https://www.googleapis.com/auth/cloud-platform'],
  lifetime=500)


storage_client = storage.Client(credentials=target_credentials)
bucket = storage_client.bucket(bucket_name)
blob = bucket.blob(blob_name)

url = blob.generate_signed_url(
    version="v4",
    expiration=datetime.timedelta(minutes=10),
    method="GET",
)

print("Generated PUT signed URL:")
print(url)
```


and separtely you an get access and id_tokens to via the same mechanism

https://gist.github.com/salrashid123/a4c2d665a4a7be910abe40a1bd425c53

**Comment by haizaar** [comment]
Great news. Happy to see it's now pythonically supported.

It still would be great if you can fix your "keyless" sample one way of the other. WDYT? - ppl still bump into it and get confused (keyless signing is still a black magic documentation wise)

**Comment by salrashid123** [comment]
no prob. just update your PR and i'll merge it in

**Comment by salrashid123** [comment]
thanks!

**Comment by haizaar** [comment]
Too early :) 
Updating docs...

**Pull request merged**
